type_index:
    path:     /
    defaults: { _controller: "SystemBackendBundle:Type:index" }
    methods:  GET

type_new:
    path:     /new
    defaults: { _controller: "SystemBackendBundle:Type:new" }
    methods:  [GET, POST]

type_edit:
    path:     /{id}/edit
    defaults: { _controller: "SystemBackendBundle:Type:edit" }
    methods:  [GET, POST]

type_delete:
    path:     /{id}/delete
    defaults: { _controller: "SystemBackendBundle:Type:delete" }
#    methods:  DELETE
