<?php

namespace System\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarksRepository extends EntityRepository
{
}
