<?php

namespace System\MovementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IntalationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntalationRepository extends EntityRepository
{
}
